name = "memo_state"
version = "1.0.0"

description = "Functional-style cached computations and effects!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "scott2000", repo = "memo_state" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
